---
- name: Install PostgreSQL Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql{{ pgsql.major_version }}-server
    - postgresql{{ pgsql.major_version }}
    - libpq5


- name: Install Patroni Packages
  yum:
    name: patroni
    state: present

