---
- name: Uninstall Repmgr Packages
  yum:
    name: "{{ repmgr_package }}"
    state: present


- name: Uninstall PostgreSQL Packages
  yum:
    name: "{{ postgresql_server_package }}"
    state: absent
    enablerepo: "{{ postgres_repo_name }}"
  # when: repmgr_install_postgresql|bool


#- name: Download and Install GPG Key
#  rpm_key:
#    state: absent
#    key: https://ftp.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL
#  # when: repmgr_install_postgresql|bool
#  # key: https://download.postgresql.org/pub/repos/yum/keys/RPM-GPG-KEY-PGDG


#- name: Ensure PostgreSQL Repository
#  yum_repository:
#    name: "{{ postgres_repo_name }}"
#    description: PostgreSQL repository
#    baseurl: "{{ postgres_repo }}"
#  # when: repmgr_install_postgresql|bool

